# Generated by Django 2.2.5 on 2019-09-22 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pastebin', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paste',
            old_name='name',
            new_name='title',
        ),
    ]
